remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
title: Hailey Cantwell - Professional Portfolio
description: Welcome to Hailey Cantwell's GitHub Page! Explore my projects, research, and skills.
